FROM node:current-slim

# Update base image and apply security patches
RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y \
    chromium \
    chromium-driver \
    git \
    && rm -rf /var/lib/apt/lists/* \
    && npm install -g npm@latest snyk@latest sonarqube-scanner

# Set PATH for Chromedriver
ENV PATH="/usr/lib/chromium:/usr/lib/chromium-driver:$PATH"

# Set working directory
WORKDIR /app